kind: Pod
apiVersion: v1
metadata:
  name: fiopod-tempssd
  namespace: acstor
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: Standard_E8s_v3
  containers:
    - name: fio
      image: nixery.dev/shell/fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ephemeralvolume
  volumes:
    - name: ephemeralvolume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-ephemeral-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "acstor-ephemeraldisk" # replace with the name of your storage class if different
            resources:
              requests: 
                storage: 1Gi