kind: Pod
apiVersion: v1
metadata:
  name: fiopod-nvme
spec:
  nodeSelector:
    acstor.azure.com/io-engine: acstor
  containers:
    - name: fio
      image: nixery.dev/shell/fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ephemeralvolume
  volumes:
    - name: ephemeralvolume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-ephemeral-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "acstor-ephemeraldisk-nvme" # replace with the name of your storage class if different
            resources:
              requests:
                storage: 1Gi
  tolerations:
  - key: "nvme"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"