apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-anf-secret
type: Opaque
stringData:
  clientID: #CHANGE TO THE CORRECT VALUE FOR YOUR ENVIRONMENT
  clientSecret: #CHANGE TO THE CORRECT VALUE FOR YOUR ENVIRONMENT