apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsiplugin-pvc
  namespace: aksesan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: san-volume
  selector:
    matchExpressions:
      - key: name
        operator: In
        values: ["data-iscsiplugin"]