---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsiplugin-pv
  labels:
    name: data-iscsiplugin
spec:
  storageClassName: san-volume
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: iscsi.csi.k8s.io
    volumeHandle: iscsi-data-id
    volumeAttributes:
      # targetPortal: "yourTargetPortal:yourTargetPortalPort"
      targetPortal: "es-us4x0sdws2z1.z42.blob.storage.azure.net:3260"
      portals: "[]"
      # iqn: "yourIQN"
      iqn: "iqn.2024-06.net.windows.core.blob.ElasticSan.es-us4x0sdws2z1:aksstoragelabsanvol"
      lun: "0"
      iscsiInterface: "default"
      discoveryCHAPAuth: "true"
      sessionCHAPAuth: "false"