apiVersion: v1
kind: Service
metadata:
  name: esan-nginx-service
  namespace: aksesan
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: esan-nginx